[package]
authors = ["Jacob Brown <kardeiz@gmail.com>"]
edition = "2018"
name = "jsonrpc-v2"
version = "0.3.1"
description = "JSONRPC 2.0 server"
keywords = ["jsonrpc", "json-rpc", "jsonrpc2", "rpc"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/kardeiz/jsonrpc-v2"

[features]
easy_errors = []

[dependencies]
bytes = "0.4"
erased-serde = "0.3"
futures = "0.1"
actix-web = "1"
actix-service = "0.4"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.serde_json]
features = ["raw_value"]
version = "1"

[dev-dependencies]

bytes = "0.4.11"
http = "0.1.15"
tokio = "0.1.15"
